// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/header.vue')['default']
    'Mdi:alertOutline': typeof import('virtual:vite-icons/mdi/alert-outline')['default']
  }
}

export { }
